name : Integración Continua

on:
    push:
        branches: ["main","master"]

jobs:
    testeo:
        runs-on: ubuntu-latest

        steps:
            - name: Obtener el codigo
              uses: actions/checkout@v4
            - name: Configurar Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'

            - name: Instalar dependencias
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install pytest pytest-django
            - name: Ejecutar pruebas con pytest
              run: |
                cd Sena
                pytest apl/tests.py --ds=config.settings
 
